spring.application.name=0.0.1


server.port=8080

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres-db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# ===============================
# actiar las migraciones de flyway
# ===============================
spring.flyway.enabled=true

# ===============================
# JWT - Configuración de autenticación
# ===============================

# Clave secreta utilizada para firmar y validar los JWT.
app.jwt.secret=<xJpMIvVgh4ydIvB00Gblem7SOoRUKumtIltw0iFJT72XQ+UWm+b9ENZ8Wonzfd6iWR0+OxxtwaKeXvPs9cUt2A==

# Tiempo de expiración del JWT en milisegundos.
# 86400000 ms = 24 horas.
app.jwt.expiration-ms=86400000

# Nombre de la cookie donde se almacenará el JWT.
app.jwt.cookie-name=jwt

# Ruta donde la cookie estará disponible.
# "/" significa que se enviará para todas las rutas del dominio.
app.jwt.cookie-path=/

# Indica si la cookie solo debe enviarse mediante HTTPS.
# false = permite HTTP, útil para desarrollo local.
# En producción debería utilizarse true.
app.jwt.cookie-secure=false

# Política SameSite de la cookie.
# Lax evita que el navegador envíe la cookie en la mayoría
# de solicitudes realizadas desde sitios de terceros.
# Esto ayuda a reducir el riesgo de ataques CSRF.
#
# Lax permite que la cookie se envíe normalmente en solicitudes
# del mismo sitio y en algunas navegaciones desde otros sitios.
app.jwt.cookie-same-site=Lax