apiVersion: v1
kind: Service
metadata:
  name: biblioteca-service
  namespace: biblioteca
  labels:
    app.kubernetes.io/name: biblioteca
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: biblioteca
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
